//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUTOHLT.MOBILE.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AUTOHLT.MOBILE.Resources.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string _1000000 {
            get {
                return ResourceManager.GetString("1000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _1000001 {
            get {
                return ResourceManager.GetString("1000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string _1000002 {
            get {
                return ResourceManager.GetString("1000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a new account.
        /// </summary>
        internal static string _1000003 {
            get {
                return ResourceManager.GetString("1000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        internal static string _1000004 {
            get {
                return ResourceManager.GetString("1000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _1000005 {
            get {
                return ResourceManager.GetString("1000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _1000006 {
            get {
                return ResourceManager.GetString("1000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string _1000007 {
            get {
                return ResourceManager.GetString("1000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is processing.
        /// </summary>
        internal static string _1000008 {
            get {
                return ResourceManager.GetString("1000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string _1000009 {
            get {
                return ResourceManager.GetString("1000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string _1000010 {
            get {
                return ResourceManager.GetString("1000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string _1000011 {
            get {
                return ResourceManager.GetString("1000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string _1000012 {
            get {
                return ResourceManager.GetString("1000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string _1000013 {
            get {
                return ResourceManager.GetString("1000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string _1000014 {
            get {
                return ResourceManager.GetString("1000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string _1000015 {
            get {
                return ResourceManager.GetString("1000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string _1000016 {
            get {
                return ResourceManager.GetString("1000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string _1000017 {
            get {
                return ResourceManager.GetString("1000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surplus.
        /// </summary>
        internal static string _1000018 {
            get {
                return ResourceManager.GetString("1000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        internal static string _1000019 {
            get {
                return ResourceManager.GetString("1000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string _1000020 {
            get {
                return ResourceManager.GetString("1000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string _1000021 {
            get {
                return ResourceManager.GetString("1000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string _1000022 {
            get {
                return ResourceManager.GetString("1000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string _1000023 {
            get {
                return ResourceManager.GetString("1000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up.
        /// </summary>
        internal static string _1000024 {
            get {
                return ResourceManager.GetString("1000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service.
        /// </summary>
        internal static string _1000025 {
            get {
                return ResourceManager.GetString("1000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive.
        /// </summary>
        internal static string _1000026 {
            get {
                return ResourceManager.GetString("1000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string _1000027 {
            get {
                return ResourceManager.GetString("1000027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service management section.
        /// </summary>
        internal static string _1000028 {
            get {
                return ResourceManager.GetString("1000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff Like.
        /// </summary>
        internal static string _1000029 {
            get {
                return ResourceManager.GetString("1000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff View.
        /// </summary>
        internal static string _1000030 {
            get {
                return ResourceManager.GetString("1000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff Share.
        /// </summary>
        internal static string _1000031 {
            get {
                return ResourceManager.GetString("1000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff Comment.
        /// </summary>
        internal static string _1000032 {
            get {
                return ResourceManager.GetString("1000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff Follow.
        /// </summary>
        internal static string _1000033 {
            get {
                return ResourceManager.GetString("1000033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service history.
        /// </summary>
        internal static string _1000034 {
            get {
                return ResourceManager.GetString("1000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string _1000035 {
            get {
                return ResourceManager.GetString("1000035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors arise during processing.
        /// </summary>
        internal static string _1000036 {
            get {
                return ResourceManager.GetString("1000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exists.
        /// </summary>
        internal static string _1000037 {
            get {
                return ResourceManager.GetString("1000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be over 6 characters.
        /// </summary>
        internal static string _1000038 {
            get {
                return ResourceManager.GetString("1000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect.
        /// </summary>
        internal static string _1000039 {
            get {
                return ResourceManager.GetString("1000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string _1000040 {
            get {
                return ResourceManager.GetString("1000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string _1000041 {
            get {
                return ResourceManager.GetString("1000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to sign out of your account !.
        /// </summary>
        internal static string _1000042 {
            get {
                return ResourceManager.GetString("1000042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        internal static string _1000043 {
            get {
                return ResourceManager.GetString("1000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount money.
        /// </summary>
        internal static string _1000044 {
            get {
                return ResourceManager.GetString("1000044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to contacts.
        /// </summary>
        internal static string _1000045 {
            get {
                return ResourceManager.GetString("1000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist.
        /// </summary>
        internal static string _1000046 {
            get {
                return ResourceManager.GetString("1000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money transfer is successful.
        /// </summary>
        internal static string _1000047 {
            get {
                return ResourceManager.GetString("1000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of money is greater than the amount you have.
        /// </summary>
        internal static string _1000048 {
            get {
                return ResourceManager.GetString("1000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service pack.
        /// </summary>
        internal static string _1000049 {
            get {
                return ResourceManager.GetString("1000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _1000050 {
            get {
                return ResourceManager.GetString("1000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _1000051 {
            get {
                return ResourceManager.GetString("1000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Service.
        /// </summary>
        internal static string _1000052 {
            get {
                return ResourceManager.GetString("1000052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the service.
        /// </summary>
        internal static string _1000053 {
            get {
                return ResourceManager.GetString("1000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forever.
        /// </summary>
        internal static string _1000054 {
            get {
                return ResourceManager.GetString("1000054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year.
        /// </summary>
        internal static string _1000055 {
            get {
                return ResourceManager.GetString("1000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string _1000056 {
            get {
                return ResourceManager.GetString("1000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You buy service {0} {1} / day {2} for {3} VND.
        /// </summary>
        internal static string _1000057 {
            get {
                return ResourceManager.GetString("1000057", resourceCulture);
            }
        }
    }
}
