//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUTOHLT.WEB.API.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bsoft_autohltEntities : DbContext
    {
        public bsoft_autohltEntities()
            : base("name=bsoft_autohltEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int AddNotification(string content, Nullable<System.Guid> id_send, Nullable<System.Guid> id_receive, Nullable<int> noti_Type, Nullable<System.DateTime> date)
        {
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var id_sendParameter = id_send.HasValue ?
                new ObjectParameter("Id_send", id_send) :
                new ObjectParameter("Id_send", typeof(System.Guid));
    
            var id_receiveParameter = id_receive.HasValue ?
                new ObjectParameter("Id_receive", id_receive) :
                new ObjectParameter("Id_receive", typeof(System.Guid));
    
            var noti_TypeParameter = noti_Type.HasValue ?
                new ObjectParameter("Noti_Type", noti_Type) :
                new ObjectParameter("Noti_Type", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNotification", contentParameter, id_sendParameter, id_receiveParameter, noti_TypeParameter, dateParameter);
        }
    
        public virtual int AddProductType(string productName, Nullable<int> price, Nullable<int> endDate, string content, Nullable<int> number)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(int));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProductType", productNameParameter, priceParameter, endDateParameter, contentParameter, numberParameter);
        }
    
        public virtual int AddServiceUseHistory(Nullable<System.Guid> id_ProType, string content, Nullable<System.Guid> id_User, Nullable<int> number, Nullable<System.DateTime> date)
        {
            var id_ProTypeParameter = id_ProType.HasValue ?
                new ObjectParameter("Id_ProType", id_ProType) :
                new ObjectParameter("Id_ProType", typeof(System.Guid));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var id_UserParameter = id_User.HasValue ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(System.Guid));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddServiceUseHistory", id_ProTypeParameter, contentParameter, id_UserParameter, numberParameter, dateParameter);
        }
    
        public virtual int AddTransferMoney(Nullable<double> discount, Nullable<int> price, Nullable<System.Guid> id_send, Nullable<System.Guid> id_receive, Nullable<int> transferType)
        {
            var discountParameter = discount.HasValue ?
                new ObjectParameter("Discount", discount) :
                new ObjectParameter("Discount", typeof(double));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            var id_sendParameter = id_send.HasValue ?
                new ObjectParameter("Id_send", id_send) :
                new ObjectParameter("Id_send", typeof(System.Guid));
    
            var id_receiveParameter = id_receive.HasValue ?
                new ObjectParameter("Id_receive", id_receive) :
                new ObjectParameter("Id_receive", typeof(System.Guid));
    
            var transferTypeParameter = transferType.HasValue ?
                new ObjectParameter("TransferType", transferType) :
                new ObjectParameter("TransferType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddTransferMoney", discountParameter, priceParameter, id_sendParameter, id_receiveParameter, transferTypeParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> CheckUserName(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("CheckUserName", usernameParameter);
        }
    
        public virtual int DeleteProductType(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductType", idParameter);
        }
    
        public virtual int DeleteRegisterProduct(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRegisterProduct", idParameter);
        }
    
        public virtual int DeleteUser(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", userNameParameter);
        }
    
        public virtual ObjectResult<GetAllHistoryUserSevice_Result> GetAllHistoryUserSevice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllHistoryUserSevice_Result>("GetAllHistoryUserSevice");
        }
    
        public virtual ObjectResult<GetAllProductType_Result> GetAllProductType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProductType_Result>("GetAllProductType");
        }
    
        public virtual ObjectResult<GetAllTransferMoney_Result> GetAllTransferMoney()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTransferMoney_Result>("GetAllTransferMoney");
        }
    
        public virtual ObjectResult<GetAllUser_Result> GetAllUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUser_Result>("GetAllUser");
        }
    
        public virtual ObjectResult<GetHistoryService_Result> GetHistoryService(Nullable<System.Guid> id_user)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("Id_user", id_user) :
                new ObjectParameter("Id_user", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHistoryService_Result>("GetHistoryService", id_userParameter);
        }
    
        public virtual ObjectResult<GetNotificationUser_Result> GetNotificationUser(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNotificationUser_Result>("GetNotificationUser", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetPriceUser(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetPriceUser", userNameParameter);
        }
    
        public virtual ObjectResult<ListRegisterProduct_Result> ListRegisterProduct(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListRegisterProduct_Result>("ListRegisterProduct", idParameter);
        }
    
        public virtual ObjectResult<NotificationDetail_Result> NotificationDetail(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotificationDetail_Result>("NotificationDetail", idParameter);
        }
    
        public virtual int RegisterProduct(Nullable<System.Guid> id_product, Nullable<System.Guid> id_User)
        {
            var id_productParameter = id_product.HasValue ?
                new ObjectParameter("Id_product", id_product) :
                new ObjectParameter("Id_product", typeof(System.Guid));
    
            var id_UserParameter = id_User.HasValue ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegisterProduct", id_productParameter, id_UserParameter);
        }
    
        public virtual int RegistrationAccount(string userName, string password, string name, Nullable<int> numberPhone, string email, Nullable<int> sex, Nullable<int> age, Nullable<System.DateTime> dateCreate)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberPhoneParameter = numberPhone.HasValue ?
                new ObjectParameter("NumberPhone", numberPhone) :
                new ObjectParameter("NumberPhone", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(int));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var dateCreateParameter = dateCreate.HasValue ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrationAccount", userNameParameter, passwordParameter, nameParameter, numberPhoneParameter, emailParameter, sexParameter, ageParameter, dateCreateParameter);
        }
    
        public virtual int UpdateProductType(Nullable<System.Guid> id, string producName, Nullable<int> price, Nullable<int> endDate, string content, Nullable<int> number)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var producNameParameter = producName != null ?
                new ObjectParameter("ProducName", producName) :
                new ObjectParameter("ProducName", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(int));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProductType", idParameter, producNameParameter, priceParameter, endDateParameter, contentParameter, numberParameter);
        }
    
        public virtual int UpdateReadNotification(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateReadNotification", idParameter);
        }
    
        public virtual int UpdateUser(string userName, string password, string name, Nullable<int> numberPhone, string email, Nullable<int> sex, Nullable<int> role, Nullable<bool> isActive, Nullable<int> age, Nullable<int> price, string idDevice)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numberPhoneParameter = numberPhone.HasValue ?
                new ObjectParameter("NumberPhone", numberPhone) :
                new ObjectParameter("NumberPhone", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(int));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            var idDeviceParameter = idDevice != null ?
                new ObjectParameter("IdDevice", idDevice) :
                new ObjectParameter("IdDevice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", userNameParameter, passwordParameter, nameParameter, numberPhoneParameter, emailParameter, sexParameter, roleParameter, isActiveParameter, ageParameter, priceParameter, idDeviceParameter);
        }
    
        public virtual ObjectResult<UserInformation_Result> UserInformation(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserInformation_Result>("UserInformation", userNameParameter, passwordParameter);
        }
    
        public virtual int UserTransfers(Nullable<System.Guid> iD_Send, Nullable<System.Guid> iD_Receive, Nullable<int> price)
        {
            var iD_SendParameter = iD_Send.HasValue ?
                new ObjectParameter("ID_Send", iD_Send) :
                new ObjectParameter("ID_Send", typeof(System.Guid));
    
            var iD_ReceiveParameter = iD_Receive.HasValue ?
                new ObjectParameter("ID_Receive", iD_Receive) :
                new ObjectParameter("ID_Receive", typeof(System.Guid));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserTransfers", iD_SendParameter, iD_ReceiveParameter, priceParameter);
        }
    }
}
